//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Crtk
{
    [Serializable]
    public class StringStampedMsg : Message
    {
        public const string k_RosMessageName = "crtk_msgs/StringStamped";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public string @string;

        public StringStampedMsg()
        {
            this.header = new HeaderMsg();
            this.@string = "";
        }

        public StringStampedMsg(HeaderMsg header, string @string)
        {
            this.header = header;
            this.@string = @string;
        }

        public static StringStampedMsg Deserialize(MessageDeserializer deserializer) => new StringStampedMsg(deserializer);

        private StringStampedMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.@string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.@string);
        }

        public override string ToString()
        {
            return "StringStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\n@string: " + @string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
