//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Cisst
{
    [Serializable]
    public class BoolStampedMsg : Message
    {
        public const string k_RosMessageName = "cisst_msgs/BoolStamped";
        public override string RosMessageName => k_RosMessageName;

        //  A Pose with reference coordinate frame and timestamp
        public HeaderMsg header;
        public bool data;

        public BoolStampedMsg()
        {
            this.header = new HeaderMsg();
            this.data = false;
        }

        public BoolStampedMsg(HeaderMsg header, bool data)
        {
            this.header = header;
            this.data = data;
        }

        public static BoolStampedMsg Deserialize(MessageDeserializer deserializer) => new BoolStampedMsg(deserializer);

        private BoolStampedMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "BoolStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
