//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Cisst
{
    [Serializable]
    public class VctDoubleVecMsg : Message
    {
        public const string k_RosMessageName = "cisst_msgs/vctDoubleVec";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public double[] data;

        public VctDoubleVecMsg()
        {
            this.header = new HeaderMsg();
            this.data = new double[0];
        }

        public VctDoubleVecMsg(HeaderMsg header, double[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static VctDoubleVecMsg Deserialize(MessageDeserializer deserializer) => new VctDoubleVecMsg(deserializer);

        private VctDoubleVecMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "VctDoubleVecMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
